services:
  quotient:
    build:
      context: .
      dockerfile: Dockerfile
    
    ports:
      - "6000:6000"

    restart: always
    container_name: quotient-main-bot
    env_file:
      - ./quotient-main.env
    
    volumes:
      - ./logs/quotient.log:/logs/quotient.log


  pro:
    build:
      context: .
      dockerfile: Dockerfile

    restart: always
    container_name: quotient-pro-bot
    env_file:
      - ./quotient-pro.env
    
    volumes:
      - ./logs/pro.log:/logs/pro.log
