[tool.poetry]
name = "quotient-bot"
version = "3.5.0"
description = ""
authors = ["deadaf <askpygod@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = {git = "https://github.com/Rapptz/discord.py.git"}
tortoise-orm = "^0.17.6"
colorama = "^0.4.4"
asyncpg = "^0.22.0"
dateparser = "^1.0.0"
discord-ext-menus = "^1.1"
aerich = "^0.5.3"
parsedatetime = "^2.6"
Pillow = "^8.2.0"
"mystbin.py" = "^2.1.3"
prettytable = "^2.1.0"
psutil = "^5.8.0"
PyNaCl = "^1.4.0"
Quart = "^0.15.1"
requests = "^2.25.1"
dblpy = "^0.4.0"
jishaku = "^2.2.0"
humanize = "^3.11.0"
pygit2 = "^1.6.1"
async-property = "^0.2.1"
colour = "^0.1.5"
imgkit = "^1.2.2"

[tool.poetry.dev-dependencies]
black = {version = "^21.5b1", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 122